// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/api"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/configuration"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/department"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/dictionary"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/dictionarydetail"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/menu"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/oauthprovider"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/position"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/role"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/schema"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/tenant"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/tenantplan"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/token"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apiMixin := schema.API{}.Mixin()
	apiMixinFields0 := apiMixin[0].Fields()
	_ = apiMixinFields0
	apiFields := schema.API{}.Fields()
	_ = apiFields
	// apiDescCreatedAt is the schema descriptor for created_at field.
	apiDescCreatedAt := apiMixinFields0[1].Descriptor()
	// api.DefaultCreatedAt holds the default value on creation for the created_at field.
	api.DefaultCreatedAt = apiDescCreatedAt.Default.(func() time.Time)
	// apiDescUpdatedAt is the schema descriptor for updated_at field.
	apiDescUpdatedAt := apiMixinFields0[2].Descriptor()
	// api.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	api.DefaultUpdatedAt = apiDescUpdatedAt.Default.(func() time.Time)
	// api.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	api.UpdateDefaultUpdatedAt = apiDescUpdatedAt.UpdateDefault.(func() time.Time)
	// apiDescServiceName is the schema descriptor for service_name field.
	apiDescServiceName := apiFields[3].Descriptor()
	// api.DefaultServiceName holds the default value on creation for the service_name field.
	api.DefaultServiceName = apiDescServiceName.Default.(string)
	// apiDescMethod is the schema descriptor for method field.
	apiDescMethod := apiFields[4].Descriptor()
	// api.DefaultMethod holds the default value on creation for the method field.
	api.DefaultMethod = apiDescMethod.Default.(string)
	// apiDescIsRequired is the schema descriptor for is_required field.
	apiDescIsRequired := apiFields[5].Descriptor()
	// api.DefaultIsRequired holds the default value on creation for the is_required field.
	api.DefaultIsRequired = apiDescIsRequired.Default.(bool)
	// apiDescID is the schema descriptor for id field.
	apiDescID := apiMixinFields0[0].Descriptor()
	// api.DefaultID holds the default value on creation for the id field.
	api.DefaultID = apiDescID.Default.(uint64)
	configurationMixin := schema.Configuration{}.Mixin()
	configurationMixinFields0 := configurationMixin[0].Fields()
	_ = configurationMixinFields0
	configurationMixinFields1 := configurationMixin[1].Fields()
	_ = configurationMixinFields1
	configurationMixinFields2 := configurationMixin[2].Fields()
	_ = configurationMixinFields2
	configurationFields := schema.Configuration{}.Fields()
	_ = configurationFields
	// configurationDescCreatedAt is the schema descriptor for created_at field.
	configurationDescCreatedAt := configurationMixinFields0[1].Descriptor()
	// configuration.DefaultCreatedAt holds the default value on creation for the created_at field.
	configuration.DefaultCreatedAt = configurationDescCreatedAt.Default.(func() time.Time)
	// configurationDescUpdatedAt is the schema descriptor for updated_at field.
	configurationDescUpdatedAt := configurationMixinFields0[2].Descriptor()
	// configuration.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	configuration.DefaultUpdatedAt = configurationDescUpdatedAt.Default.(func() time.Time)
	// configuration.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	configuration.UpdateDefaultUpdatedAt = configurationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// configurationDescSort is the schema descriptor for sort field.
	configurationDescSort := configurationMixinFields1[0].Descriptor()
	// configuration.DefaultSort holds the default value on creation for the sort field.
	configuration.DefaultSort = configurationDescSort.Default.(uint32)
	// configurationDescState is the schema descriptor for state field.
	configurationDescState := configurationMixinFields2[0].Descriptor()
	// configuration.DefaultState holds the default value on creation for the state field.
	configuration.DefaultState = configurationDescState.Default.(bool)
	// configurationDescID is the schema descriptor for id field.
	configurationDescID := configurationMixinFields0[0].Descriptor()
	// configuration.DefaultID holds the default value on creation for the id field.
	configuration.DefaultID = configurationDescID.Default.(uint64)
	departmentMixin := schema.Department{}.Mixin()
	departmentMixinFields0 := departmentMixin[0].Fields()
	_ = departmentMixinFields0
	departmentMixinFields1 := departmentMixin[1].Fields()
	_ = departmentMixinFields1
	departmentMixinFields2 := departmentMixin[2].Fields()
	_ = departmentMixinFields2
	departmentMixinFields3 := departmentMixin[3].Fields()
	_ = departmentMixinFields3
	departmentFields := schema.Department{}.Fields()
	_ = departmentFields
	// departmentDescCreatedAt is the schema descriptor for created_at field.
	departmentDescCreatedAt := departmentMixinFields0[1].Descriptor()
	// department.DefaultCreatedAt holds the default value on creation for the created_at field.
	department.DefaultCreatedAt = departmentDescCreatedAt.Default.(func() time.Time)
	// departmentDescUpdatedAt is the schema descriptor for updated_at field.
	departmentDescUpdatedAt := departmentMixinFields0[2].Descriptor()
	// department.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	department.DefaultUpdatedAt = departmentDescUpdatedAt.Default.(func() time.Time)
	// department.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	department.UpdateDefaultUpdatedAt = departmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// departmentDescTenantID is the schema descriptor for tenant_id field.
	departmentDescTenantID := departmentMixinFields1[0].Descriptor()
	// department.DefaultTenantID holds the default value on creation for the tenant_id field.
	department.DefaultTenantID = departmentDescTenantID.Default.(uint64)
	// departmentDescStatus is the schema descriptor for status field.
	departmentDescStatus := departmentMixinFields2[0].Descriptor()
	// department.DefaultStatus holds the default value on creation for the status field.
	department.DefaultStatus = departmentDescStatus.Default.(uint8)
	// departmentDescSort is the schema descriptor for sort field.
	departmentDescSort := departmentMixinFields3[0].Descriptor()
	// department.DefaultSort holds the default value on creation for the sort field.
	department.DefaultSort = departmentDescSort.Default.(uint32)
	// departmentDescLeader is the schema descriptor for leader field.
	departmentDescLeader := departmentFields[2].Descriptor()
	// department.DefaultLeader holds the default value on creation for the leader field.
	department.DefaultLeader = departmentDescLeader.Default.(uint64)
	// departmentDescParentID is the schema descriptor for parent_id field.
	departmentDescParentID := departmentFields[6].Descriptor()
	// department.DefaultParentID holds the default value on creation for the parent_id field.
	department.DefaultParentID = departmentDescParentID.Default.(uint64)
	// departmentDescID is the schema descriptor for id field.
	departmentDescID := departmentMixinFields0[0].Descriptor()
	// department.DefaultID holds the default value on creation for the id field.
	department.DefaultID = departmentDescID.Default.(uint64)
	dictionaryMixin := schema.Dictionary{}.Mixin()
	dictionaryMixinFields0 := dictionaryMixin[0].Fields()
	_ = dictionaryMixinFields0
	dictionaryMixinFields1 := dictionaryMixin[1].Fields()
	_ = dictionaryMixinFields1
	dictionaryMixinFields2 := dictionaryMixin[2].Fields()
	_ = dictionaryMixinFields2
	dictionaryFields := schema.Dictionary{}.Fields()
	_ = dictionaryFields
	// dictionaryDescCreatedAt is the schema descriptor for created_at field.
	dictionaryDescCreatedAt := dictionaryMixinFields0[1].Descriptor()
	// dictionary.DefaultCreatedAt holds the default value on creation for the created_at field.
	dictionary.DefaultCreatedAt = dictionaryDescCreatedAt.Default.(func() time.Time)
	// dictionaryDescUpdatedAt is the schema descriptor for updated_at field.
	dictionaryDescUpdatedAt := dictionaryMixinFields0[2].Descriptor()
	// dictionary.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dictionary.DefaultUpdatedAt = dictionaryDescUpdatedAt.Default.(func() time.Time)
	// dictionary.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dictionary.UpdateDefaultUpdatedAt = dictionaryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// dictionaryDescStatus is the schema descriptor for status field.
	dictionaryDescStatus := dictionaryMixinFields1[0].Descriptor()
	// dictionary.DefaultStatus holds the default value on creation for the status field.
	dictionary.DefaultStatus = dictionaryDescStatus.Default.(uint8)
	// dictionaryDescTenantID is the schema descriptor for tenant_id field.
	dictionaryDescTenantID := dictionaryMixinFields2[0].Descriptor()
	// dictionary.DefaultTenantID holds the default value on creation for the tenant_id field.
	dictionary.DefaultTenantID = dictionaryDescTenantID.Default.(uint64)
	// dictionaryDescIsPublic is the schema descriptor for is_public field.
	dictionaryDescIsPublic := dictionaryFields[3].Descriptor()
	// dictionary.DefaultIsPublic holds the default value on creation for the is_public field.
	dictionary.DefaultIsPublic = dictionaryDescIsPublic.Default.(bool)
	// dictionaryDescID is the schema descriptor for id field.
	dictionaryDescID := dictionaryMixinFields0[0].Descriptor()
	// dictionary.DefaultID holds the default value on creation for the id field.
	dictionary.DefaultID = dictionaryDescID.Default.(uint64)
	dictionarydetailMixin := schema.DictionaryDetail{}.Mixin()
	dictionarydetailMixinFields0 := dictionarydetailMixin[0].Fields()
	_ = dictionarydetailMixinFields0
	dictionarydetailMixinFields1 := dictionarydetailMixin[1].Fields()
	_ = dictionarydetailMixinFields1
	dictionarydetailMixinFields2 := dictionarydetailMixin[2].Fields()
	_ = dictionarydetailMixinFields2
	dictionarydetailMixinFields3 := dictionarydetailMixin[3].Fields()
	_ = dictionarydetailMixinFields3
	dictionarydetailFields := schema.DictionaryDetail{}.Fields()
	_ = dictionarydetailFields
	// dictionarydetailDescCreatedAt is the schema descriptor for created_at field.
	dictionarydetailDescCreatedAt := dictionarydetailMixinFields0[1].Descriptor()
	// dictionarydetail.DefaultCreatedAt holds the default value on creation for the created_at field.
	dictionarydetail.DefaultCreatedAt = dictionarydetailDescCreatedAt.Default.(func() time.Time)
	// dictionarydetailDescUpdatedAt is the schema descriptor for updated_at field.
	dictionarydetailDescUpdatedAt := dictionarydetailMixinFields0[2].Descriptor()
	// dictionarydetail.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dictionarydetail.DefaultUpdatedAt = dictionarydetailDescUpdatedAt.Default.(func() time.Time)
	// dictionarydetail.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dictionarydetail.UpdateDefaultUpdatedAt = dictionarydetailDescUpdatedAt.UpdateDefault.(func() time.Time)
	// dictionarydetailDescTenantID is the schema descriptor for tenant_id field.
	dictionarydetailDescTenantID := dictionarydetailMixinFields1[0].Descriptor()
	// dictionarydetail.DefaultTenantID holds the default value on creation for the tenant_id field.
	dictionarydetail.DefaultTenantID = dictionarydetailDescTenantID.Default.(uint64)
	// dictionarydetailDescStatus is the schema descriptor for status field.
	dictionarydetailDescStatus := dictionarydetailMixinFields2[0].Descriptor()
	// dictionarydetail.DefaultStatus holds the default value on creation for the status field.
	dictionarydetail.DefaultStatus = dictionarydetailDescStatus.Default.(uint8)
	// dictionarydetailDescSort is the schema descriptor for sort field.
	dictionarydetailDescSort := dictionarydetailMixinFields3[0].Descriptor()
	// dictionarydetail.DefaultSort holds the default value on creation for the sort field.
	dictionarydetail.DefaultSort = dictionarydetailDescSort.Default.(uint32)
	// dictionarydetailDescID is the schema descriptor for id field.
	dictionarydetailDescID := dictionarydetailMixinFields0[0].Descriptor()
	// dictionarydetail.DefaultID holds the default value on creation for the id field.
	dictionarydetail.DefaultID = dictionarydetailDescID.Default.(uint64)
	menuMixin := schema.Menu{}.Mixin()
	menuMixinFields0 := menuMixin[0].Fields()
	_ = menuMixinFields0
	menuMixinFields1 := menuMixin[1].Fields()
	_ = menuMixinFields1
	menuFields := schema.Menu{}.Fields()
	_ = menuFields
	// menuDescCreatedAt is the schema descriptor for created_at field.
	menuDescCreatedAt := menuMixinFields0[1].Descriptor()
	// menu.DefaultCreatedAt holds the default value on creation for the created_at field.
	menu.DefaultCreatedAt = menuDescCreatedAt.Default.(func() time.Time)
	// menuDescUpdatedAt is the schema descriptor for updated_at field.
	menuDescUpdatedAt := menuMixinFields0[2].Descriptor()
	// menu.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	menu.DefaultUpdatedAt = menuDescUpdatedAt.Default.(func() time.Time)
	// menu.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	menu.UpdateDefaultUpdatedAt = menuDescUpdatedAt.UpdateDefault.(func() time.Time)
	// menuDescSort is the schema descriptor for sort field.
	menuDescSort := menuMixinFields1[0].Descriptor()
	// menu.DefaultSort holds the default value on creation for the sort field.
	menu.DefaultSort = menuDescSort.Default.(uint32)
	// menuDescParentID is the schema descriptor for parent_id field.
	menuDescParentID := menuFields[0].Descriptor()
	// menu.DefaultParentID holds the default value on creation for the parent_id field.
	menu.DefaultParentID = menuDescParentID.Default.(uint64)
	// menuDescPath is the schema descriptor for path field.
	menuDescPath := menuFields[3].Descriptor()
	// menu.DefaultPath holds the default value on creation for the path field.
	menu.DefaultPath = menuDescPath.Default.(string)
	// menuDescRedirect is the schema descriptor for redirect field.
	menuDescRedirect := menuFields[5].Descriptor()
	// menu.DefaultRedirect holds the default value on creation for the redirect field.
	menu.DefaultRedirect = menuDescRedirect.Default.(string)
	// menuDescComponent is the schema descriptor for component field.
	menuDescComponent := menuFields[6].Descriptor()
	// menu.DefaultComponent holds the default value on creation for the component field.
	menu.DefaultComponent = menuDescComponent.Default.(string)
	// menuDescDisabled is the schema descriptor for disabled field.
	menuDescDisabled := menuFields[7].Descriptor()
	// menu.DefaultDisabled holds the default value on creation for the disabled field.
	menu.DefaultDisabled = menuDescDisabled.Default.(bool)
	// menuDescServiceName is the schema descriptor for service_name field.
	menuDescServiceName := menuFields[8].Descriptor()
	// menu.DefaultServiceName holds the default value on creation for the service_name field.
	menu.DefaultServiceName = menuDescServiceName.Default.(string)
	// menuDescHideMenu is the schema descriptor for hide_menu field.
	menuDescHideMenu := menuFields[12].Descriptor()
	// menu.DefaultHideMenu holds the default value on creation for the hide_menu field.
	menu.DefaultHideMenu = menuDescHideMenu.Default.(bool)
	// menuDescHideBreadcrumb is the schema descriptor for hide_breadcrumb field.
	menuDescHideBreadcrumb := menuFields[13].Descriptor()
	// menu.DefaultHideBreadcrumb holds the default value on creation for the hide_breadcrumb field.
	menu.DefaultHideBreadcrumb = menuDescHideBreadcrumb.Default.(bool)
	// menuDescIgnoreKeepAlive is the schema descriptor for ignore_keep_alive field.
	menuDescIgnoreKeepAlive := menuFields[14].Descriptor()
	// menu.DefaultIgnoreKeepAlive holds the default value on creation for the ignore_keep_alive field.
	menu.DefaultIgnoreKeepAlive = menuDescIgnoreKeepAlive.Default.(bool)
	// menuDescHideTab is the schema descriptor for hide_tab field.
	menuDescHideTab := menuFields[15].Descriptor()
	// menu.DefaultHideTab holds the default value on creation for the hide_tab field.
	menu.DefaultHideTab = menuDescHideTab.Default.(bool)
	// menuDescFrameSrc is the schema descriptor for frame_src field.
	menuDescFrameSrc := menuFields[16].Descriptor()
	// menu.DefaultFrameSrc holds the default value on creation for the frame_src field.
	menu.DefaultFrameSrc = menuDescFrameSrc.Default.(string)
	// menuDescCarryParam is the schema descriptor for carry_param field.
	menuDescCarryParam := menuFields[17].Descriptor()
	// menu.DefaultCarryParam holds the default value on creation for the carry_param field.
	menu.DefaultCarryParam = menuDescCarryParam.Default.(bool)
	// menuDescHideChildrenInMenu is the schema descriptor for hide_children_in_menu field.
	menuDescHideChildrenInMenu := menuFields[18].Descriptor()
	// menu.DefaultHideChildrenInMenu holds the default value on creation for the hide_children_in_menu field.
	menu.DefaultHideChildrenInMenu = menuDescHideChildrenInMenu.Default.(bool)
	// menuDescAffix is the schema descriptor for affix field.
	menuDescAffix := menuFields[19].Descriptor()
	// menu.DefaultAffix holds the default value on creation for the affix field.
	menu.DefaultAffix = menuDescAffix.Default.(bool)
	// menuDescDynamicLevel is the schema descriptor for dynamic_level field.
	menuDescDynamicLevel := menuFields[20].Descriptor()
	// menu.DefaultDynamicLevel holds the default value on creation for the dynamic_level field.
	menu.DefaultDynamicLevel = menuDescDynamicLevel.Default.(uint32)
	// menuDescRealPath is the schema descriptor for real_path field.
	menuDescRealPath := menuFields[21].Descriptor()
	// menu.DefaultRealPath holds the default value on creation for the real_path field.
	menu.DefaultRealPath = menuDescRealPath.Default.(string)
	// menuDescID is the schema descriptor for id field.
	menuDescID := menuMixinFields0[0].Descriptor()
	// menu.DefaultID holds the default value on creation for the id field.
	menu.DefaultID = menuDescID.Default.(uint64)
	oauthproviderMixin := schema.OauthProvider{}.Mixin()
	oauthproviderMixinFields0 := oauthproviderMixin[0].Fields()
	_ = oauthproviderMixinFields0
	oauthproviderFields := schema.OauthProvider{}.Fields()
	_ = oauthproviderFields
	// oauthproviderDescCreatedAt is the schema descriptor for created_at field.
	oauthproviderDescCreatedAt := oauthproviderMixinFields0[1].Descriptor()
	// oauthprovider.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthprovider.DefaultCreatedAt = oauthproviderDescCreatedAt.Default.(func() time.Time)
	// oauthproviderDescUpdatedAt is the schema descriptor for updated_at field.
	oauthproviderDescUpdatedAt := oauthproviderMixinFields0[2].Descriptor()
	// oauthprovider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oauthprovider.DefaultUpdatedAt = oauthproviderDescUpdatedAt.Default.(func() time.Time)
	// oauthprovider.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oauthprovider.UpdateDefaultUpdatedAt = oauthproviderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// oauthproviderDescID is the schema descriptor for id field.
	oauthproviderDescID := oauthproviderMixinFields0[0].Descriptor()
	// oauthprovider.DefaultID holds the default value on creation for the id field.
	oauthprovider.DefaultID = oauthproviderDescID.Default.(uint64)
	positionMixin := schema.Position{}.Mixin()
	positionMixinFields0 := positionMixin[0].Fields()
	_ = positionMixinFields0
	positionMixinFields1 := positionMixin[1].Fields()
	_ = positionMixinFields1
	positionMixinFields2 := positionMixin[2].Fields()
	_ = positionMixinFields2
	positionMixinFields3 := positionMixin[3].Fields()
	_ = positionMixinFields3
	positionFields := schema.Position{}.Fields()
	_ = positionFields
	// positionDescCreatedAt is the schema descriptor for created_at field.
	positionDescCreatedAt := positionMixinFields0[1].Descriptor()
	// position.DefaultCreatedAt holds the default value on creation for the created_at field.
	position.DefaultCreatedAt = positionDescCreatedAt.Default.(func() time.Time)
	// positionDescUpdatedAt is the schema descriptor for updated_at field.
	positionDescUpdatedAt := positionMixinFields0[2].Descriptor()
	// position.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	position.DefaultUpdatedAt = positionDescUpdatedAt.Default.(func() time.Time)
	// position.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	position.UpdateDefaultUpdatedAt = positionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// positionDescTenantID is the schema descriptor for tenant_id field.
	positionDescTenantID := positionMixinFields1[0].Descriptor()
	// position.DefaultTenantID holds the default value on creation for the tenant_id field.
	position.DefaultTenantID = positionDescTenantID.Default.(uint64)
	// positionDescStatus is the schema descriptor for status field.
	positionDescStatus := positionMixinFields2[0].Descriptor()
	// position.DefaultStatus holds the default value on creation for the status field.
	position.DefaultStatus = positionDescStatus.Default.(uint8)
	// positionDescSort is the schema descriptor for sort field.
	positionDescSort := positionMixinFields3[0].Descriptor()
	// position.DefaultSort holds the default value on creation for the sort field.
	position.DefaultSort = positionDescSort.Default.(uint32)
	// positionDescID is the schema descriptor for id field.
	positionDescID := positionMixinFields0[0].Descriptor()
	// position.DefaultID holds the default value on creation for the id field.
	position.DefaultID = positionDescID.Default.(uint64)
	roleMixin := schema.Role{}.Mixin()
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleMixinFields1 := roleMixin[1].Fields()
	_ = roleMixinFields1
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields0[1].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields0[2].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescStatus is the schema descriptor for status field.
	roleDescStatus := roleMixinFields1[0].Descriptor()
	// role.DefaultStatus holds the default value on creation for the status field.
	role.DefaultStatus = roleDescStatus.Default.(uint8)
	// roleDescRemark is the schema descriptor for remark field.
	roleDescRemark := roleFields[2].Descriptor()
	// role.DefaultRemark holds the default value on creation for the remark field.
	role.DefaultRemark = roleDescRemark.Default.(string)
	// roleDescSort is the schema descriptor for sort field.
	roleDescSort := roleFields[3].Descriptor()
	// role.DefaultSort holds the default value on creation for the sort field.
	role.DefaultSort = roleDescSort.Default.(uint32)
	// roleDescID is the schema descriptor for id field.
	roleDescID := roleMixinFields0[0].Descriptor()
	// role.DefaultID holds the default value on creation for the id field.
	role.DefaultID = roleDescID.Default.(uint64)
	tenantMixin := schema.Tenant{}.Mixin()
	tenantMixinFields0 := tenantMixin[0].Fields()
	_ = tenantMixinFields0
	tenantMixinFields1 := tenantMixin[1].Fields()
	_ = tenantMixinFields1
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantMixinFields0[1].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantMixinFields0[2].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantDescStatus is the schema descriptor for status field.
	tenantDescStatus := tenantMixinFields1[0].Descriptor()
	// tenant.DefaultStatus holds the default value on creation for the status field.
	tenant.DefaultStatus = tenantDescStatus.Default.(uint8)
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[0].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = func() func(string) error {
		validators := tenantDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescCode is the schema descriptor for code field.
	tenantDescCode := tenantFields[1].Descriptor()
	// tenant.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	tenant.CodeValidator = func() func(string) error {
		validators := tenantDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescAdminID is the schema descriptor for admin_id field.
	tenantDescAdminID := tenantFields[11].Descriptor()
	// tenant.AdminIDValidator is a validator for the "admin_id" field. It is called by the builders before save.
	tenant.AdminIDValidator = tenantDescAdminID.Validators[0].(func(int64) error)
	// tenantDescParentID is the schema descriptor for parent_id field.
	tenantDescParentID := tenantFields[12].Descriptor()
	// tenant.DefaultParentID holds the default value on creation for the parent_id field.
	tenant.DefaultParentID = tenantDescParentID.Default.(int64)
	// tenant.ParentIDValidator is a validator for the "parent_id" field. It is called by the builders before save.
	tenant.ParentIDValidator = tenantDescParentID.Validators[0].(func(int64) error)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantMixinFields0[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(uint64)
	tenantplanMixin := schema.TenantPlan{}.Mixin()
	tenantplanMixinFields0 := tenantplanMixin[0].Fields()
	_ = tenantplanMixinFields0
	tenantplanMixinFields1 := tenantplanMixin[1].Fields()
	_ = tenantplanMixinFields1
	tenantplanFields := schema.TenantPlan{}.Fields()
	_ = tenantplanFields
	// tenantplanDescCreatedAt is the schema descriptor for created_at field.
	tenantplanDescCreatedAt := tenantplanMixinFields0[1].Descriptor()
	// tenantplan.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenantplan.DefaultCreatedAt = tenantplanDescCreatedAt.Default.(func() time.Time)
	// tenantplanDescUpdatedAt is the schema descriptor for updated_at field.
	tenantplanDescUpdatedAt := tenantplanMixinFields0[2].Descriptor()
	// tenantplan.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenantplan.DefaultUpdatedAt = tenantplanDescUpdatedAt.Default.(func() time.Time)
	// tenantplan.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenantplan.UpdateDefaultUpdatedAt = tenantplanDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantplanDescStatus is the schema descriptor for status field.
	tenantplanDescStatus := tenantplanMixinFields1[0].Descriptor()
	// tenantplan.DefaultStatus holds the default value on creation for the status field.
	tenantplan.DefaultStatus = tenantplanDescStatus.Default.(uint8)
	// tenantplanDescID is the schema descriptor for id field.
	tenantplanDescID := tenantplanMixinFields0[0].Descriptor()
	// tenantplan.DefaultID holds the default value on creation for the id field.
	tenantplan.DefaultID = tenantplanDescID.Default.(uint64)
	tokenMixin := schema.Token{}.Mixin()
	tokenMixinFields0 := tokenMixin[0].Fields()
	_ = tokenMixinFields0
	tokenMixinFields1 := tokenMixin[1].Fields()
	_ = tokenMixinFields1
	tokenFields := schema.Token{}.Fields()
	_ = tokenFields
	// tokenDescCreatedAt is the schema descriptor for created_at field.
	tokenDescCreatedAt := tokenMixinFields0[1].Descriptor()
	// token.DefaultCreatedAt holds the default value on creation for the created_at field.
	token.DefaultCreatedAt = tokenDescCreatedAt.Default.(func() time.Time)
	// tokenDescUpdatedAt is the schema descriptor for updated_at field.
	tokenDescUpdatedAt := tokenMixinFields0[2].Descriptor()
	// token.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	token.DefaultUpdatedAt = tokenDescUpdatedAt.Default.(func() time.Time)
	// token.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	token.UpdateDefaultUpdatedAt = tokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tokenDescStatus is the schema descriptor for status field.
	tokenDescStatus := tokenMixinFields1[0].Descriptor()
	// token.DefaultStatus holds the default value on creation for the status field.
	token.DefaultStatus = tokenDescStatus.Default.(uint8)
	// tokenDescUserID is the schema descriptor for user_id field.
	tokenDescUserID := tokenFields[0].Descriptor()
	// token.DefaultUserID holds the default value on creation for the user_id field.
	token.DefaultUserID = tokenDescUserID.Default.(uint64)
	// tokenDescUsername is the schema descriptor for username field.
	tokenDescUsername := tokenFields[1].Descriptor()
	// token.DefaultUsername holds the default value on creation for the username field.
	token.DefaultUsername = tokenDescUsername.Default.(string)
	// tokenDescID is the schema descriptor for id field.
	tokenDescID := tokenMixinFields0[0].Descriptor()
	// token.DefaultID holds the default value on creation for the id field.
	token.DefaultID = tokenDescID.Default.(uint64)
	userMixin := schema.User{}.Mixin()
	userMixinHooks4 := userMixin[4].Hooks()
	user.Hooks[0] = userMixinHooks4[0]
	userMixinInters2 := userMixin[2].Interceptors()
	userMixinInters4 := userMixin[4].Interceptors()
	user.Interceptors[0] = userMixinInters2[0]
	user.Interceptors[1] = userMixinInters4[0]
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userMixinFields3 := userMixin[3].Fields()
	_ = userMixinFields3
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescTenantID is the schema descriptor for tenant_id field.
	userDescTenantID := userMixinFields1[0].Descriptor()
	// user.DefaultTenantID holds the default value on creation for the tenant_id field.
	user.DefaultTenantID = userDescTenantID.Default.(uint64)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userMixinFields3[0].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(uint8)
	// userDescHomePath is the schema descriptor for home_path field.
	userDescHomePath := userFields[4].Descriptor()
	// user.DefaultHomePath holds the default value on creation for the home_path field.
	user.DefaultHomePath = userDescHomePath.Default.(string)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(uint64)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
