// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/tenantplan"
)

// tenant Table | 租户套餐计划表
type TenantPlan struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Create Time | 创建日期
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Update Time | 修改日期
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Status 1: normal 2: ban | 状态 1 正常 2 禁用
	Status uint8 `json:"status,omitempty"`
	// 套餐名称
	PackageName string `json:"package_name,omitempty"`
	// 菜单ID
	MenuIds []string `json:"menu_ids,omitempty"`
	// 备注
	Remark []string `json:"remark,omitempty"`
	// 菜单树选择项是否关联显示
	MenuCheckStrictly int `json:"menu_check_strictly,omitempty"`
	selectValues      sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TenantPlan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tenantplan.FieldMenuIds, tenantplan.FieldRemark:
			values[i] = new([]byte)
		case tenantplan.FieldID, tenantplan.FieldStatus, tenantplan.FieldMenuCheckStrictly:
			values[i] = new(sql.NullInt64)
		case tenantplan.FieldPackageName:
			values[i] = new(sql.NullString)
		case tenantplan.FieldCreatedAt, tenantplan.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TenantPlan fields.
func (_m *TenantPlan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tenantplan.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case tenantplan.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case tenantplan.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case tenantplan.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = uint8(value.Int64)
			}
		case tenantplan.FieldPackageName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field package_name", values[i])
			} else if value.Valid {
				_m.PackageName = value.String
			}
		case tenantplan.FieldMenuIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field menu_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.MenuIds); err != nil {
					return fmt.Errorf("unmarshal field menu_ids: %w", err)
				}
			}
		case tenantplan.FieldRemark:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Remark); err != nil {
					return fmt.Errorf("unmarshal field remark: %w", err)
				}
			}
		case tenantplan.FieldMenuCheckStrictly:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field menu_check_strictly", values[i])
			} else if value.Valid {
				_m.MenuCheckStrictly = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TenantPlan.
// This includes values selected through modifiers, order, etc.
func (_m *TenantPlan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TenantPlan.
// Note that you need to call TenantPlan.Unwrap() before calling this method if this TenantPlan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TenantPlan) Update() *TenantPlanUpdateOne {
	return NewTenantPlanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TenantPlan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TenantPlan) Unwrap() *TenantPlan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TenantPlan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TenantPlan) String() string {
	var builder strings.Builder
	builder.WriteString("TenantPlan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("package_name=")
	builder.WriteString(_m.PackageName)
	builder.WriteString(", ")
	builder.WriteString("menu_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.MenuIds))
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(fmt.Sprintf("%v", _m.Remark))
	builder.WriteString(", ")
	builder.WriteString("menu_check_strictly=")
	builder.WriteString(fmt.Sprintf("%v", _m.MenuCheckStrictly))
	builder.WriteByte(')')
	return builder.String()
}

// TenantPlans is a parsable slice of TenantPlan.
type TenantPlans []*TenantPlan
