// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/predicate"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/tenant"
)

// TenantUpdate is the builder for updating Tenant entities.
type TenantUpdate struct {
	config
	hooks     []Hook
	mutation  *TenantMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdate) Where(ps ...predicate.Tenant) *TenantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdate) SetUpdatedAt(v time.Time) *TenantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdate) SetStatus(v uint8) *TenantUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableStatus(v *uint8) *TenantUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *TenantUpdate) AddStatus(v int8) *TenantUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *TenantUpdate) ClearStatus() *TenantUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetName sets the "name" field.
func (_u *TenantUpdate) SetName(v string) *TenantUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableName(v *string) *TenantUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *TenantUpdate) SetCode(v string) *TenantUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableCode(v *string) *TenantUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetContactPhone sets the "contact_phone" field.
func (_u *TenantUpdate) SetContactPhone(v string) *TenantUpdate {
	_u.mutation.SetContactPhone(v)
	return _u
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableContactPhone(v *string) *TenantUpdate {
	if v != nil {
		_u.SetContactPhone(*v)
	}
	return _u
}

// SetContactEmail sets the "contact_email" field.
func (_u *TenantUpdate) SetContactEmail(v string) *TenantUpdate {
	_u.mutation.SetContactEmail(v)
	return _u
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableContactEmail(v *string) *TenantUpdate {
	if v != nil {
		_u.SetContactEmail(*v)
	}
	return _u
}

// ClearContactEmail clears the value of the "contact_email" field.
func (_u *TenantUpdate) ClearContactEmail() *TenantUpdate {
	_u.mutation.ClearContactEmail()
	return _u
}

// SetCompanyName sets the "company_name" field.
func (_u *TenantUpdate) SetCompanyName(v string) *TenantUpdate {
	_u.mutation.SetCompanyName(v)
	return _u
}

// SetNillableCompanyName sets the "company_name" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableCompanyName(v *string) *TenantUpdate {
	if v != nil {
		_u.SetCompanyName(*v)
	}
	return _u
}

// ClearCompanyName clears the value of the "company_name" field.
func (_u *TenantUpdate) ClearCompanyName() *TenantUpdate {
	_u.mutation.ClearCompanyName()
	return _u
}

// SetLicenseNumber sets the "license_number" field.
func (_u *TenantUpdate) SetLicenseNumber(v string) *TenantUpdate {
	_u.mutation.SetLicenseNumber(v)
	return _u
}

// SetNillableLicenseNumber sets the "license_number" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableLicenseNumber(v *string) *TenantUpdate {
	if v != nil {
		_u.SetLicenseNumber(*v)
	}
	return _u
}

// ClearLicenseNumber clears the value of the "license_number" field.
func (_u *TenantUpdate) ClearLicenseNumber() *TenantUpdate {
	_u.mutation.ClearLicenseNumber()
	return _u
}

// SetAddress sets the "address" field.
func (_u *TenantUpdate) SetAddress(v string) *TenantUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableAddress(v *string) *TenantUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *TenantUpdate) ClearAddress() *TenantUpdate {
	_u.mutation.ClearAddress()
	return _u
}

// SetIntro sets the "intro" field.
func (_u *TenantUpdate) SetIntro(v string) *TenantUpdate {
	_u.mutation.SetIntro(v)
	return _u
}

// SetNillableIntro sets the "intro" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableIntro(v *string) *TenantUpdate {
	if v != nil {
		_u.SetIntro(*v)
	}
	return _u
}

// ClearIntro clears the value of the "intro" field.
func (_u *TenantUpdate) ClearIntro() *TenantUpdate {
	_u.mutation.ClearIntro()
	return _u
}

// SetDomain sets the "domain" field.
func (_u *TenantUpdate) SetDomain(v string) *TenantUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableDomain(v *string) *TenantUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *TenantUpdate) ClearDomain() *TenantUpdate {
	_u.mutation.ClearDomain()
	return _u
}

// SetLevel sets the "level" field.
func (_u *TenantUpdate) SetLevel(v uint32) *TenantUpdate {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableLevel(v *uint32) *TenantUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *TenantUpdate) AddLevel(v int32) *TenantUpdate {
	_u.mutation.AddLevel(v)
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *TenantUpdate) SetPlanID(v int64) *TenantUpdate {
	_u.mutation.ResetPlanID()
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *TenantUpdate) SetNillablePlanID(v *int64) *TenantUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// AddPlanID adds value to the "plan_id" field.
func (_u *TenantUpdate) AddPlanID(v int64) *TenantUpdate {
	_u.mutation.AddPlanID(v)
	return _u
}

// ClearPlanID clears the value of the "plan_id" field.
func (_u *TenantUpdate) ClearPlanID() *TenantUpdate {
	_u.mutation.ClearPlanID()
	return _u
}

// SetAdminID sets the "admin_id" field.
func (_u *TenantUpdate) SetAdminID(v int64) *TenantUpdate {
	_u.mutation.ResetAdminID()
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableAdminID(v *int64) *TenantUpdate {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// AddAdminID adds value to the "admin_id" field.
func (_u *TenantUpdate) AddAdminID(v int64) *TenantUpdate {
	_u.mutation.AddAdminID(v)
	return _u
}

// ClearAdminID clears the value of the "admin_id" field.
func (_u *TenantUpdate) ClearAdminID() *TenantUpdate {
	_u.mutation.ClearAdminID()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *TenantUpdate) SetParentID(v int64) *TenantUpdate {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableParentID(v *int64) *TenantUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *TenantUpdate) AddParentID(v int64) *TenantUpdate {
	_u.mutation.AddParentID(v)
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *TenantUpdate) ClearParentID() *TenantUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdate) Mutation() *TenantMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := tenant.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Tenant.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AdminID(); ok {
		if err := tenant.AdminIDValidator(v); err != nil {
			return &ValidationError{Name: "admin_id", err: fmt.Errorf(`ent: validator failed for field "Tenant.admin_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TenantUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TenantUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TenantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(tenant.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(tenant.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(tenant.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactPhone(); ok {
		_spec.SetField(tenant.FieldContactPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactEmail(); ok {
		_spec.SetField(tenant.FieldContactEmail, field.TypeString, value)
	}
	if _u.mutation.ContactEmailCleared() {
		_spec.ClearField(tenant.FieldContactEmail, field.TypeString)
	}
	if value, ok := _u.mutation.CompanyName(); ok {
		_spec.SetField(tenant.FieldCompanyName, field.TypeString, value)
	}
	if _u.mutation.CompanyNameCleared() {
		_spec.ClearField(tenant.FieldCompanyName, field.TypeString)
	}
	if value, ok := _u.mutation.LicenseNumber(); ok {
		_spec.SetField(tenant.FieldLicenseNumber, field.TypeString, value)
	}
	if _u.mutation.LicenseNumberCleared() {
		_spec.ClearField(tenant.FieldLicenseNumber, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(tenant.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(tenant.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.Intro(); ok {
		_spec.SetField(tenant.FieldIntro, field.TypeString, value)
	}
	if _u.mutation.IntroCleared() {
		_spec.ClearField(tenant.FieldIntro, field.TypeString)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(tenant.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(tenant.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(tenant.FieldLevel, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(tenant.FieldLevel, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.PlanID(); ok {
		_spec.SetField(tenant.FieldPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlanID(); ok {
		_spec.AddField(tenant.FieldPlanID, field.TypeInt64, value)
	}
	if _u.mutation.PlanIDCleared() {
		_spec.ClearField(tenant.FieldPlanID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AdminID(); ok {
		_spec.SetField(tenant.FieldAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAdminID(); ok {
		_spec.AddField(tenant.FieldAdminID, field.TypeInt64, value)
	}
	if _u.mutation.AdminIDCleared() {
		_spec.ClearField(tenant.FieldAdminID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(tenant.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(tenant.FieldParentID, field.TypeInt64, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(tenant.FieldParentID, field.TypeInt64)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantUpdateOne is the builder for updating a single Tenant entity.
type TenantUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TenantMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdateOne) SetUpdatedAt(v time.Time) *TenantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdateOne) SetStatus(v uint8) *TenantUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableStatus(v *uint8) *TenantUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *TenantUpdateOne) AddStatus(v int8) *TenantUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *TenantUpdateOne) ClearStatus() *TenantUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetName sets the "name" field.
func (_u *TenantUpdateOne) SetName(v string) *TenantUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableName(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *TenantUpdateOne) SetCode(v string) *TenantUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableCode(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetContactPhone sets the "contact_phone" field.
func (_u *TenantUpdateOne) SetContactPhone(v string) *TenantUpdateOne {
	_u.mutation.SetContactPhone(v)
	return _u
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableContactPhone(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetContactPhone(*v)
	}
	return _u
}

// SetContactEmail sets the "contact_email" field.
func (_u *TenantUpdateOne) SetContactEmail(v string) *TenantUpdateOne {
	_u.mutation.SetContactEmail(v)
	return _u
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableContactEmail(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetContactEmail(*v)
	}
	return _u
}

// ClearContactEmail clears the value of the "contact_email" field.
func (_u *TenantUpdateOne) ClearContactEmail() *TenantUpdateOne {
	_u.mutation.ClearContactEmail()
	return _u
}

// SetCompanyName sets the "company_name" field.
func (_u *TenantUpdateOne) SetCompanyName(v string) *TenantUpdateOne {
	_u.mutation.SetCompanyName(v)
	return _u
}

// SetNillableCompanyName sets the "company_name" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableCompanyName(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetCompanyName(*v)
	}
	return _u
}

// ClearCompanyName clears the value of the "company_name" field.
func (_u *TenantUpdateOne) ClearCompanyName() *TenantUpdateOne {
	_u.mutation.ClearCompanyName()
	return _u
}

// SetLicenseNumber sets the "license_number" field.
func (_u *TenantUpdateOne) SetLicenseNumber(v string) *TenantUpdateOne {
	_u.mutation.SetLicenseNumber(v)
	return _u
}

// SetNillableLicenseNumber sets the "license_number" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableLicenseNumber(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetLicenseNumber(*v)
	}
	return _u
}

// ClearLicenseNumber clears the value of the "license_number" field.
func (_u *TenantUpdateOne) ClearLicenseNumber() *TenantUpdateOne {
	_u.mutation.ClearLicenseNumber()
	return _u
}

// SetAddress sets the "address" field.
func (_u *TenantUpdateOne) SetAddress(v string) *TenantUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableAddress(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *TenantUpdateOne) ClearAddress() *TenantUpdateOne {
	_u.mutation.ClearAddress()
	return _u
}

// SetIntro sets the "intro" field.
func (_u *TenantUpdateOne) SetIntro(v string) *TenantUpdateOne {
	_u.mutation.SetIntro(v)
	return _u
}

// SetNillableIntro sets the "intro" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableIntro(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetIntro(*v)
	}
	return _u
}

// ClearIntro clears the value of the "intro" field.
func (_u *TenantUpdateOne) ClearIntro() *TenantUpdateOne {
	_u.mutation.ClearIntro()
	return _u
}

// SetDomain sets the "domain" field.
func (_u *TenantUpdateOne) SetDomain(v string) *TenantUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableDomain(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *TenantUpdateOne) ClearDomain() *TenantUpdateOne {
	_u.mutation.ClearDomain()
	return _u
}

// SetLevel sets the "level" field.
func (_u *TenantUpdateOne) SetLevel(v uint32) *TenantUpdateOne {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableLevel(v *uint32) *TenantUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *TenantUpdateOne) AddLevel(v int32) *TenantUpdateOne {
	_u.mutation.AddLevel(v)
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *TenantUpdateOne) SetPlanID(v int64) *TenantUpdateOne {
	_u.mutation.ResetPlanID()
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillablePlanID(v *int64) *TenantUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// AddPlanID adds value to the "plan_id" field.
func (_u *TenantUpdateOne) AddPlanID(v int64) *TenantUpdateOne {
	_u.mutation.AddPlanID(v)
	return _u
}

// ClearPlanID clears the value of the "plan_id" field.
func (_u *TenantUpdateOne) ClearPlanID() *TenantUpdateOne {
	_u.mutation.ClearPlanID()
	return _u
}

// SetAdminID sets the "admin_id" field.
func (_u *TenantUpdateOne) SetAdminID(v int64) *TenantUpdateOne {
	_u.mutation.ResetAdminID()
	_u.mutation.SetAdminID(v)
	return _u
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableAdminID(v *int64) *TenantUpdateOne {
	if v != nil {
		_u.SetAdminID(*v)
	}
	return _u
}

// AddAdminID adds value to the "admin_id" field.
func (_u *TenantUpdateOne) AddAdminID(v int64) *TenantUpdateOne {
	_u.mutation.AddAdminID(v)
	return _u
}

// ClearAdminID clears the value of the "admin_id" field.
func (_u *TenantUpdateOne) ClearAdminID() *TenantUpdateOne {
	_u.mutation.ClearAdminID()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *TenantUpdateOne) SetParentID(v int64) *TenantUpdateOne {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableParentID(v *int64) *TenantUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *TenantUpdateOne) AddParentID(v int64) *TenantUpdateOne {
	_u.mutation.AddParentID(v)
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *TenantUpdateOne) ClearParentID() *TenantUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdateOne) Mutation() *TenantMutation {
	return _u.mutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdateOne) Where(ps ...predicate.Tenant) *TenantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantUpdateOne) Select(field string, fields ...string) *TenantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tenant entity.
func (_u *TenantUpdateOne) Save(ctx context.Context) (*Tenant, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdateOne) SaveX(ctx context.Context) *Tenant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := tenant.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Tenant.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AdminID(); ok {
		if err := tenant.AdminIDValidator(v); err != nil {
			return &ValidationError{Name: "admin_id", err: fmt.Errorf(`ent: validator failed for field "Tenant.admin_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TenantUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TenantUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TenantUpdateOne) sqlSave(ctx context.Context) (_node *Tenant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tenant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenant.FieldID)
		for _, f := range fields {
			if !tenant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(tenant.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(tenant.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(tenant.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactPhone(); ok {
		_spec.SetField(tenant.FieldContactPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactEmail(); ok {
		_spec.SetField(tenant.FieldContactEmail, field.TypeString, value)
	}
	if _u.mutation.ContactEmailCleared() {
		_spec.ClearField(tenant.FieldContactEmail, field.TypeString)
	}
	if value, ok := _u.mutation.CompanyName(); ok {
		_spec.SetField(tenant.FieldCompanyName, field.TypeString, value)
	}
	if _u.mutation.CompanyNameCleared() {
		_spec.ClearField(tenant.FieldCompanyName, field.TypeString)
	}
	if value, ok := _u.mutation.LicenseNumber(); ok {
		_spec.SetField(tenant.FieldLicenseNumber, field.TypeString, value)
	}
	if _u.mutation.LicenseNumberCleared() {
		_spec.ClearField(tenant.FieldLicenseNumber, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(tenant.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(tenant.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.Intro(); ok {
		_spec.SetField(tenant.FieldIntro, field.TypeString, value)
	}
	if _u.mutation.IntroCleared() {
		_spec.ClearField(tenant.FieldIntro, field.TypeString)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(tenant.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(tenant.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(tenant.FieldLevel, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(tenant.FieldLevel, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.PlanID(); ok {
		_spec.SetField(tenant.FieldPlanID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlanID(); ok {
		_spec.AddField(tenant.FieldPlanID, field.TypeInt64, value)
	}
	if _u.mutation.PlanIDCleared() {
		_spec.ClearField(tenant.FieldPlanID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AdminID(); ok {
		_spec.SetField(tenant.FieldAdminID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAdminID(); ok {
		_spec.AddField(tenant.FieldAdminID, field.TypeInt64, value)
	}
	if _u.mutation.AdminIDCleared() {
		_spec.ClearField(tenant.FieldAdminID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(tenant.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(tenant.FieldParentID, field.TypeInt64, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(tenant.FieldParentID, field.TypeInt64)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Tenant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
