// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/predicate"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/tenantplan"
)

// TenantPlanUpdate is the builder for updating TenantPlan entities.
type TenantPlanUpdate struct {
	config
	hooks     []Hook
	mutation  *TenantPlanMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TenantPlanUpdate builder.
func (_u *TenantPlanUpdate) Where(ps ...predicate.TenantPlan) *TenantPlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantPlanUpdate) SetUpdatedAt(v time.Time) *TenantPlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantPlanUpdate) SetStatus(v uint8) *TenantPlanUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantPlanUpdate) SetNillableStatus(v *uint8) *TenantPlanUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *TenantPlanUpdate) AddStatus(v int8) *TenantPlanUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *TenantPlanUpdate) ClearStatus() *TenantPlanUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetPackageName sets the "package_name" field.
func (_u *TenantPlanUpdate) SetPackageName(v string) *TenantPlanUpdate {
	_u.mutation.SetPackageName(v)
	return _u
}

// SetNillablePackageName sets the "package_name" field if the given value is not nil.
func (_u *TenantPlanUpdate) SetNillablePackageName(v *string) *TenantPlanUpdate {
	if v != nil {
		_u.SetPackageName(*v)
	}
	return _u
}

// SetMenuIds sets the "menu_ids" field.
func (_u *TenantPlanUpdate) SetMenuIds(v []string) *TenantPlanUpdate {
	_u.mutation.SetMenuIds(v)
	return _u
}

// AppendMenuIds appends value to the "menu_ids" field.
func (_u *TenantPlanUpdate) AppendMenuIds(v []string) *TenantPlanUpdate {
	_u.mutation.AppendMenuIds(v)
	return _u
}

// SetRemark sets the "remark" field.
func (_u *TenantPlanUpdate) SetRemark(v []string) *TenantPlanUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// AppendRemark appends value to the "remark" field.
func (_u *TenantPlanUpdate) AppendRemark(v []string) *TenantPlanUpdate {
	_u.mutation.AppendRemark(v)
	return _u
}

// SetMenuCheckStrictly sets the "menu_check_strictly" field.
func (_u *TenantPlanUpdate) SetMenuCheckStrictly(v int) *TenantPlanUpdate {
	_u.mutation.ResetMenuCheckStrictly()
	_u.mutation.SetMenuCheckStrictly(v)
	return _u
}

// SetNillableMenuCheckStrictly sets the "menu_check_strictly" field if the given value is not nil.
func (_u *TenantPlanUpdate) SetNillableMenuCheckStrictly(v *int) *TenantPlanUpdate {
	if v != nil {
		_u.SetMenuCheckStrictly(*v)
	}
	return _u
}

// AddMenuCheckStrictly adds value to the "menu_check_strictly" field.
func (_u *TenantPlanUpdate) AddMenuCheckStrictly(v int) *TenantPlanUpdate {
	_u.mutation.AddMenuCheckStrictly(v)
	return _u
}

// Mutation returns the TenantPlanMutation object of the builder.
func (_u *TenantPlanUpdate) Mutation() *TenantPlanMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantPlanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantPlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantPlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantPlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantPlanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenantplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TenantPlanUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TenantPlanUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TenantPlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(tenantplan.Table, tenantplan.Columns, sqlgraph.NewFieldSpec(tenantplan.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenantplan.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(tenantplan.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(tenantplan.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.PackageName(); ok {
		_spec.SetField(tenantplan.FieldPackageName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MenuIds(); ok {
		_spec.SetField(tenantplan.FieldMenuIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMenuIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenantplan.FieldMenuIds, value)
		})
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(tenantplan.FieldRemark, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRemark(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenantplan.FieldRemark, value)
		})
	}
	if value, ok := _u.mutation.MenuCheckStrictly(); ok {
		_spec.SetField(tenantplan.FieldMenuCheckStrictly, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMenuCheckStrictly(); ok {
		_spec.AddField(tenantplan.FieldMenuCheckStrictly, field.TypeInt, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantPlanUpdateOne is the builder for updating a single TenantPlan entity.
type TenantPlanUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TenantPlanMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantPlanUpdateOne) SetUpdatedAt(v time.Time) *TenantPlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantPlanUpdateOne) SetStatus(v uint8) *TenantPlanUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantPlanUpdateOne) SetNillableStatus(v *uint8) *TenantPlanUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *TenantPlanUpdateOne) AddStatus(v int8) *TenantPlanUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *TenantPlanUpdateOne) ClearStatus() *TenantPlanUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetPackageName sets the "package_name" field.
func (_u *TenantPlanUpdateOne) SetPackageName(v string) *TenantPlanUpdateOne {
	_u.mutation.SetPackageName(v)
	return _u
}

// SetNillablePackageName sets the "package_name" field if the given value is not nil.
func (_u *TenantPlanUpdateOne) SetNillablePackageName(v *string) *TenantPlanUpdateOne {
	if v != nil {
		_u.SetPackageName(*v)
	}
	return _u
}

// SetMenuIds sets the "menu_ids" field.
func (_u *TenantPlanUpdateOne) SetMenuIds(v []string) *TenantPlanUpdateOne {
	_u.mutation.SetMenuIds(v)
	return _u
}

// AppendMenuIds appends value to the "menu_ids" field.
func (_u *TenantPlanUpdateOne) AppendMenuIds(v []string) *TenantPlanUpdateOne {
	_u.mutation.AppendMenuIds(v)
	return _u
}

// SetRemark sets the "remark" field.
func (_u *TenantPlanUpdateOne) SetRemark(v []string) *TenantPlanUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// AppendRemark appends value to the "remark" field.
func (_u *TenantPlanUpdateOne) AppendRemark(v []string) *TenantPlanUpdateOne {
	_u.mutation.AppendRemark(v)
	return _u
}

// SetMenuCheckStrictly sets the "menu_check_strictly" field.
func (_u *TenantPlanUpdateOne) SetMenuCheckStrictly(v int) *TenantPlanUpdateOne {
	_u.mutation.ResetMenuCheckStrictly()
	_u.mutation.SetMenuCheckStrictly(v)
	return _u
}

// SetNillableMenuCheckStrictly sets the "menu_check_strictly" field if the given value is not nil.
func (_u *TenantPlanUpdateOne) SetNillableMenuCheckStrictly(v *int) *TenantPlanUpdateOne {
	if v != nil {
		_u.SetMenuCheckStrictly(*v)
	}
	return _u
}

// AddMenuCheckStrictly adds value to the "menu_check_strictly" field.
func (_u *TenantPlanUpdateOne) AddMenuCheckStrictly(v int) *TenantPlanUpdateOne {
	_u.mutation.AddMenuCheckStrictly(v)
	return _u
}

// Mutation returns the TenantPlanMutation object of the builder.
func (_u *TenantPlanUpdateOne) Mutation() *TenantPlanMutation {
	return _u.mutation
}

// Where appends a list predicates to the TenantPlanUpdate builder.
func (_u *TenantPlanUpdateOne) Where(ps ...predicate.TenantPlan) *TenantPlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantPlanUpdateOne) Select(field string, fields ...string) *TenantPlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TenantPlan entity.
func (_u *TenantPlanUpdateOne) Save(ctx context.Context) (*TenantPlan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantPlanUpdateOne) SaveX(ctx context.Context) *TenantPlan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantPlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantPlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantPlanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenantplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TenantPlanUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TenantPlanUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TenantPlanUpdateOne) sqlSave(ctx context.Context) (_node *TenantPlan, err error) {
	_spec := sqlgraph.NewUpdateSpec(tenantplan.Table, tenantplan.Columns, sqlgraph.NewFieldSpec(tenantplan.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenantPlan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenantplan.FieldID)
		for _, f := range fields {
			if !tenantplan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenantplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenantplan.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(tenantplan.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(tenantplan.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.PackageName(); ok {
		_spec.SetField(tenantplan.FieldPackageName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MenuIds(); ok {
		_spec.SetField(tenantplan.FieldMenuIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMenuIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenantplan.FieldMenuIds, value)
		})
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(tenantplan.FieldRemark, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRemark(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, tenantplan.FieldRemark, value)
		})
	}
	if value, ok := _u.mutation.MenuCheckStrictly(); ok {
		_spec.SetField(tenantplan.FieldMenuCheckStrictly, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMenuCheckStrictly(); ok {
		_spec.AddField(tenantplan.FieldMenuCheckStrictly, field.TypeInt, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &TenantPlan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
