// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/tenant"
)

// TenantCreate is the builder for creating a Tenant entity.
type TenantCreate struct {
	config
	mutation *TenantMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *TenantCreate) SetCreatedAt(v time.Time) *TenantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TenantCreate) SetNillableCreatedAt(v *time.Time) *TenantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TenantCreate) SetUpdatedAt(v time.Time) *TenantCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TenantCreate) SetNillableUpdatedAt(v *time.Time) *TenantCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TenantCreate) SetStatus(v uint8) *TenantCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TenantCreate) SetNillableStatus(v *uint8) *TenantCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *TenantCreate) SetName(v string) *TenantCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *TenantCreate) SetCode(v string) *TenantCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetContactPhone sets the "contact_phone" field.
func (_c *TenantCreate) SetContactPhone(v string) *TenantCreate {
	_c.mutation.SetContactPhone(v)
	return _c
}

// SetContactEmail sets the "contact_email" field.
func (_c *TenantCreate) SetContactEmail(v string) *TenantCreate {
	_c.mutation.SetContactEmail(v)
	return _c
}

// SetCompanyName sets the "company_name" field.
func (_c *TenantCreate) SetCompanyName(v string) *TenantCreate {
	_c.mutation.SetCompanyName(v)
	return _c
}

// SetLicenseNumber sets the "license_number" field.
func (_c *TenantCreate) SetLicenseNumber(v string) *TenantCreate {
	_c.mutation.SetLicenseNumber(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *TenantCreate) SetAddress(v string) *TenantCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetIntro sets the "intro" field.
func (_c *TenantCreate) SetIntro(v string) *TenantCreate {
	_c.mutation.SetIntro(v)
	return _c
}

// SetDomain sets the "domain" field.
func (_c *TenantCreate) SetDomain(v string) *TenantCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetLevel sets the "level" field.
func (_c *TenantCreate) SetLevel(v int) *TenantCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *TenantCreate) SetPlanID(v int64) *TenantCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_c *TenantCreate) SetNillablePlanID(v *int64) *TenantCreate {
	if v != nil {
		_c.SetPlanID(*v)
	}
	return _c
}

// SetAdminID sets the "admin_id" field.
func (_c *TenantCreate) SetAdminID(v int64) *TenantCreate {
	_c.mutation.SetAdminID(v)
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *TenantCreate) SetParentID(v int64) *TenantCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *TenantCreate) SetID(v uint64) *TenantCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TenantCreate) SetNillableID(v *uint64) *TenantCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the TenantMutation object of the builder.
func (_c *TenantCreate) Mutation() *TenantMutation {
	return _c.mutation
}

// Save creates the Tenant in the database.
func (_c *TenantCreate) Save(ctx context.Context) (*Tenant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TenantCreate) SaveX(ctx context.Context) *Tenant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TenantCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tenant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := tenant.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := tenant.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := tenant.DefaultID
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TenantCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Tenant.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Tenant.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Tenant.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Tenant.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := tenant.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Tenant.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContactPhone(); !ok {
		return &ValidationError{Name: "contact_phone", err: errors.New(`ent: missing required field "Tenant.contact_phone"`)}
	}
	if _, ok := _c.mutation.ContactEmail(); !ok {
		return &ValidationError{Name: "contact_email", err: errors.New(`ent: missing required field "Tenant.contact_email"`)}
	}
	if _, ok := _c.mutation.CompanyName(); !ok {
		return &ValidationError{Name: "company_name", err: errors.New(`ent: missing required field "Tenant.company_name"`)}
	}
	if _, ok := _c.mutation.LicenseNumber(); !ok {
		return &ValidationError{Name: "license_number", err: errors.New(`ent: missing required field "Tenant.license_number"`)}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Tenant.address"`)}
	}
	if _, ok := _c.mutation.Intro(); !ok {
		return &ValidationError{Name: "intro", err: errors.New(`ent: missing required field "Tenant.intro"`)}
	}
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "Tenant.domain"`)}
	}
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "Tenant.level"`)}
	}
	if _, ok := _c.mutation.AdminID(); !ok {
		return &ValidationError{Name: "admin_id", err: errors.New(`ent: missing required field "Tenant.admin_id"`)}
	}
	if v, ok := _c.mutation.AdminID(); ok {
		if err := tenant.AdminIDValidator(v); err != nil {
			return &ValidationError{Name: "admin_id", err: fmt.Errorf(`ent: validator failed for field "Tenant.admin_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		return &ValidationError{Name: "parent_id", err: errors.New(`ent: missing required field "Tenant.parent_id"`)}
	}
	if v, ok := _c.mutation.ParentID(); ok {
		if err := tenant.ParentIDValidator(v); err != nil {
			return &ValidationError{Name: "parent_id", err: fmt.Errorf(`ent: validator failed for field "Tenant.parent_id": %w`, err)}
		}
	}
	return nil
}

func (_c *TenantCreate) sqlSave(ctx context.Context) (*Tenant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TenantCreate) createSpec() (*Tenant, *sqlgraph.CreateSpec) {
	var (
		_node = &Tenant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tenant.Table, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tenant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeUint8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(tenant.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.ContactPhone(); ok {
		_spec.SetField(tenant.FieldContactPhone, field.TypeString, value)
		_node.ContactPhone = value
	}
	if value, ok := _c.mutation.ContactEmail(); ok {
		_spec.SetField(tenant.FieldContactEmail, field.TypeString, value)
		_node.ContactEmail = value
	}
	if value, ok := _c.mutation.CompanyName(); ok {
		_spec.SetField(tenant.FieldCompanyName, field.TypeString, value)
		_node.CompanyName = value
	}
	if value, ok := _c.mutation.LicenseNumber(); ok {
		_spec.SetField(tenant.FieldLicenseNumber, field.TypeString, value)
		_node.LicenseNumber = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(tenant.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.Intro(); ok {
		_spec.SetField(tenant.FieldIntro, field.TypeString, value)
		_node.Intro = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(tenant.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(tenant.FieldLevel, field.TypeInt, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.PlanID(); ok {
		_spec.SetField(tenant.FieldPlanID, field.TypeInt64, value)
		_node.PlanID = value
	}
	if value, ok := _c.mutation.AdminID(); ok {
		_spec.SetField(tenant.FieldAdminID, field.TypeInt64, value)
		_node.AdminID = value
	}
	if value, ok := _c.mutation.ParentID(); ok {
		_spec.SetField(tenant.FieldParentID, field.TypeInt64, value)
		_node.ParentID = value
	}
	return _node, _spec
}

// TenantCreateBulk is the builder for creating many Tenant entities in bulk.
type TenantCreateBulk struct {
	config
	err      error
	builders []*TenantCreate
}

// Save creates the Tenant entities in the database.
func (_c *TenantCreateBulk) Save(ctx context.Context) ([]*Tenant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Tenant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TenantCreateBulk) SaveX(ctx context.Context) []*Tenant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
