// Code generated by ent, DO NOT EDIT.

package tenantplan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/saas-mingyang/mingyang-admin-core/rpc/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v uint8) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldEQ(FieldStatus, v))
}

// PackageName applies equality check predicate on the "package_name" field. It's identical to PackageNameEQ.
func PackageName(v string) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldEQ(FieldPackageName, v))
}

// MenuCheckStrictly applies equality check predicate on the "menu_check_strictly" field. It's identical to MenuCheckStrictlyEQ.
func MenuCheckStrictly(v int) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldEQ(FieldMenuCheckStrictly, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldLTE(FieldUpdatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v uint8) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v uint8) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...uint8) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...uint8) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v uint8) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v uint8) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v uint8) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v uint8) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldLTE(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldNotNull(FieldStatus))
}

// PackageNameEQ applies the EQ predicate on the "package_name" field.
func PackageNameEQ(v string) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldEQ(FieldPackageName, v))
}

// PackageNameNEQ applies the NEQ predicate on the "package_name" field.
func PackageNameNEQ(v string) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldNEQ(FieldPackageName, v))
}

// PackageNameIn applies the In predicate on the "package_name" field.
func PackageNameIn(vs ...string) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldIn(FieldPackageName, vs...))
}

// PackageNameNotIn applies the NotIn predicate on the "package_name" field.
func PackageNameNotIn(vs ...string) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldNotIn(FieldPackageName, vs...))
}

// PackageNameGT applies the GT predicate on the "package_name" field.
func PackageNameGT(v string) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldGT(FieldPackageName, v))
}

// PackageNameGTE applies the GTE predicate on the "package_name" field.
func PackageNameGTE(v string) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldGTE(FieldPackageName, v))
}

// PackageNameLT applies the LT predicate on the "package_name" field.
func PackageNameLT(v string) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldLT(FieldPackageName, v))
}

// PackageNameLTE applies the LTE predicate on the "package_name" field.
func PackageNameLTE(v string) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldLTE(FieldPackageName, v))
}

// PackageNameContains applies the Contains predicate on the "package_name" field.
func PackageNameContains(v string) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldContains(FieldPackageName, v))
}

// PackageNameHasPrefix applies the HasPrefix predicate on the "package_name" field.
func PackageNameHasPrefix(v string) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldHasPrefix(FieldPackageName, v))
}

// PackageNameHasSuffix applies the HasSuffix predicate on the "package_name" field.
func PackageNameHasSuffix(v string) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldHasSuffix(FieldPackageName, v))
}

// PackageNameEqualFold applies the EqualFold predicate on the "package_name" field.
func PackageNameEqualFold(v string) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldEqualFold(FieldPackageName, v))
}

// PackageNameContainsFold applies the ContainsFold predicate on the "package_name" field.
func PackageNameContainsFold(v string) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldContainsFold(FieldPackageName, v))
}

// MenuCheckStrictlyEQ applies the EQ predicate on the "menu_check_strictly" field.
func MenuCheckStrictlyEQ(v int) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldEQ(FieldMenuCheckStrictly, v))
}

// MenuCheckStrictlyNEQ applies the NEQ predicate on the "menu_check_strictly" field.
func MenuCheckStrictlyNEQ(v int) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldNEQ(FieldMenuCheckStrictly, v))
}

// MenuCheckStrictlyIn applies the In predicate on the "menu_check_strictly" field.
func MenuCheckStrictlyIn(vs ...int) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldIn(FieldMenuCheckStrictly, vs...))
}

// MenuCheckStrictlyNotIn applies the NotIn predicate on the "menu_check_strictly" field.
func MenuCheckStrictlyNotIn(vs ...int) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldNotIn(FieldMenuCheckStrictly, vs...))
}

// MenuCheckStrictlyGT applies the GT predicate on the "menu_check_strictly" field.
func MenuCheckStrictlyGT(v int) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldGT(FieldMenuCheckStrictly, v))
}

// MenuCheckStrictlyGTE applies the GTE predicate on the "menu_check_strictly" field.
func MenuCheckStrictlyGTE(v int) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldGTE(FieldMenuCheckStrictly, v))
}

// MenuCheckStrictlyLT applies the LT predicate on the "menu_check_strictly" field.
func MenuCheckStrictlyLT(v int) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldLT(FieldMenuCheckStrictly, v))
}

// MenuCheckStrictlyLTE applies the LTE predicate on the "menu_check_strictly" field.
func MenuCheckStrictlyLTE(v int) predicate.TenantPlan {
	return predicate.TenantPlan(sql.FieldLTE(FieldMenuCheckStrictly, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TenantPlan) predicate.TenantPlan {
	return predicate.TenantPlan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TenantPlan) predicate.TenantPlan {
	return predicate.TenantPlan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TenantPlan) predicate.TenantPlan {
	return predicate.TenantPlan(sql.NotPredicates(p))
}
